kele_mysql:
  restart: always
  image: mysql:5.6
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql/:/etc/mysql/conf.d
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=imooc
    - MYSQL_ROOT_PASSWORD=root

kele_nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/mx_nginx.conf:/etc/nginx/conf.d/mx_nginx.conf
  volumes_from:
    - kele_imooc
  links:
    - kele_imooc:web

kele_imooc:
  restart: always
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/imooc
  links:
    - kele_mysql:mysql
  command: uwsgi -s :8000 -w imooc.wsgi -p 3



