# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180302_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ols_cluster',
            field=models.IntegerField(default=0, verbose_name='OLS分类'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_communicational',
            field=models.FloatField(default=0.0, verbose_name='交流'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_global',
            field=models.FloatField(default=0.0, verbose_name='综合'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_intuitive',
            field=models.FloatField(default=0.0, verbose_name='直觉'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_motivational',
            field=models.FloatField(default=0.0, verbose_name='动机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_sensing',
            field=models.FloatField(default=0.0, verbose_name='感悟'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_sequential',
            field=models.FloatField(default=0.0, verbose_name='序列'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_verbal',
            field=models.FloatField(default=0.0, verbose_name='言语'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ols_visual',
            field=models.FloatField(default=0.0, verbose_name='视觉'),
        ),
    ]
